### ISSUE TITLE
Config not saved after importing

### ISSUE THREAD

**Issue by daethnir** [pomerium/desktop-client#122]
## What happened?

I imported a pomerium connection from json, which worked. Connected via that connection many times. Quit app.

When I re-launched pomerium desktop the connection was no longer there.

## What did you expect to happen?

The newly-imported connection would have been saved to disk along with any other endpoints that were configured.

## What's your environment like?

- Pomerium Desktop version: 0.17.1
- Server Operating System/Architecture/Cloud: Mac

## Additional context

If I import then make a new connection then both the imported and the new (dummy) connection are available after restart. So it's simply not saving the config after using the Import button.

**Comment by wasaga** [comment]
caused by https://github.com/pomerium/internal/issues/868

**Comment by vixus0** [comment]
Do you have an estimated release date for a Pomerium Desktop version that includes this fix?
