### ISSUE TITLE
listen address should be accessible from the connections list

### ISSUE THREAD

**Issue by wasaga** [pomerium/desktop-client#56]
**Is your feature request related to a problem? Please describe.**

Currently desktop client does not display a tunnel's local listener port. One has to go to individual connection details to figure it out. 

![image.png](https://images.zenhubusercontent.com/600622a9c28f517c8c6081c9/453c6323-0924-4793-8f4a-5f36425ce31d)

**Describe the solution you'd like**

A preferred solution is to provide this information directly in the list, with ability to copy it to clipboard. i.e. google cloud instance list example: 
![image.png](https://images.zenhubusercontent.com/600622a9c28f517c8c6081c9/95ad68bc-949b-4803-92f7-aa29124fa4f0)

**Comment by travisgroth** [comment]
From discussion:

- backend should default to 127.0.0.1 if address is unspecified
- when frontend receives listener info, pass it along to user unmodified (IP and Port)
- change "connected" to "listening on [address]" or "1/3 listening"
- add copy to clipboard button next to address field

**Comment by nhayfield** [comment]
todo: backend should default to 127.0.0.1 if address is unspecified

**Comment by desimone** [comment]
I think we implied it, but are we going to also default to IPv4 if unspecified?
