### ISSUE TITLE
connection destination URL confusing

### ISSUE THREAD

**Issue by calebdoxsey** [pomerium/desktop-client#68]
## What happened?
I attempted to set a destination URL like:

```
https+tcp://tcp.example.com:6379
```

But it didn't work. I believe this is because it expects an address like:

```
tcp.example.com:6379
```

So the inline documentation is wrong. Its neither a URL nor is it:

> The FROM field in a pomerium route.

## What did you expect to happen?

If we're just taking the hostname+port, then it should say `Destination Address` and the docs should be updated.

**Comment by wasaga** [comment]
https://github.com/pomerium/cli/blob/ae250e91e9b616e2675ad0312f8fd43850b581f8/proto/api.proto#L138-L139

**Comment by travisgroth** [comment]
We can call it a "destination address" and provide an example with the correct format.

**Comment by desimone** [comment]
@alexfornuto  -- I think this is fixed with #70 ? is that right?
