### ISSUE TITLE
deleting an empty folder doesn't work

### ISSUE THREAD

**Issue by desimone** [pomerium/desktop-client#71]
## What happened?

I tried deleting an empty folder. 

## What did you expect to happen?

The folder to be deleted. 

## How'd it happen?

<img width="1154" alt="Screen Shot 2022-01-09 at 8 03 25 PM" src="https://user-images.githubusercontent.com/1544881/148717240-b331f3be-584b-4d2a-9d11-6350c34be791.png">

<img width="1154" alt="Screen Shot 2022-01-09 at 8 03 33 PM" src="https://user-images.githubusercontent.com/1544881/148717244-d28c02ea-75a1-438e-a799-b0d2d6220c4e.png">

??? Nothing happens. Sometimes the order of the folders switches. 

## What's your environment like?

- Pomerium Desktop version: Version: 0.16.0- 92ad590

## Config export

n/a

## Additional context

n/a

**Comment by wasaga** [comment]
I'm still trying to reproduce it. 
You should not end up with an empty folder.

**Comment by wasaga** [comment]
still doesn't reproduce for me. we will be waiting for more insights from Sentry meanwhile. moving back to backlog.

**Comment by desimone** [comment]
I will try reproducing.

**Comment by travisgroth** [comment]
@alexfornuto was able to reproduce and will post a loom

**Comment by alexfornuto** [comment]
https://www.loom.com/share/eb74051ce93c4cefa6a1b7827adac432
