### ISSUE TITLE
Support TLS client certificate and key per connection

### ISSUE THREAD

**Issue by travisgroth** [pomerium/desktop-client#90]
**Is your feature request related to a problem? Please describe.**

The CLI will be adding support for client certificates in https://github.com/pomerium/cli/issues/35.

**Describe the solution you'd like**

The desktop UI should allow users to specify a cert and key for a given TCP connection.  

**Describe alternatives you've considered**

n/a

**Explain any additional use-cases**

n/a

**Additional context**

n/a

**Comment by wasaga** [comment]
For the UI I suggest the following: 

- if client cert is not set, provide an option to upload cert and key. 
- if client cert is set, do not show the content of the certificate, but provide an option to remove it.
