### ISSUE TITLE
Docs for new Client Cert inputs

### ISSUE THREAD

**Issue by nhayfield** [pomerium/desktop-client#95]
![new_inputs.png](https://images.zenhubusercontent.com/5fbbd387653d5124928c585a/581fda5a-a0df-4be9-a879-eb8afdf01797)

Nathan put in some placeholder help text here but modifications might be needed.
Then new inputs are on the Add Connection page under Advanced Settings.
There is a PR in to add the code but it is waiting on a release of the CLI so that it will work.

https://github.com/pomerium/desktop-client/pull/94

**Comment by alexfornuto** [comment]
@wasaga please confirm: This setting is required for TCP routes that have `tls_downstream_client_ca_file`, or if `client_ca_file` is set globally, yes?
