### ISSUE TITLE
macOS:  dock icon is tiny

### ISSUE THREAD

**Issue by desimone** [pomerium/desktop-client#99]
## What happened?

The dock bar icon is tiny. This is true on both my external and native monitor. 

## How'd it happen?

1. Start desktop app
3. Look in dock bar 
4. 🔬 

<img width="168" alt="Screen Shot 2022-02-22 at 11 33 46 AM" src="https://user-images.githubusercontent.com/1544881/156031607-6daf191c-a2b8-499c-9cb6-e8f216e8bd18.png">

<img width="1508" alt="Screen Shot 2022-02-22 at 11 37 06 AM" src="https://user-images.githubusercontent.com/1544881/156031590-6c016036-c6a4-4050-b826-44edaa191c84.png">

## What's your environment like?

- Pomerium Desktop version: Version: 0.16.2- f39bfa0 CLI Version: v0.16.1
- Mac Monterey : M1 12.2.1 (21D62)

## Config export

N/A

## Additional context

- Not really related to #97

**Comment by desimone** [comment]
Randomly working again for me. Not sure. 

<img width="457" alt="Screen Shot 2022-02-28 at 9 43 51 AM" src="https://user-images.githubusercontent.com/1544881/156032155-3bf35100-a3f4-4fd7-abc7-879ccab65f81.png">

**Comment by nhayfield** [comment]
Could be related: https://apple.stackexchange.com/questions/338881/there-is-a-tiny-icon-on-macos-dock-that-is-not-clickable

**Comment by calebdoxsey** [comment]
I also don't know how to fix this. I don't know the details of electron or macos well enough to know where the problem is. I tried re-creating icons, upgrading electron-builder and always hiding the dock, but none of those things worked.

**Comment by desimone** [comment]
I can no longer reproduce, so I'm not sure either. Closing until this pops up again 🤷
